AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/linked_list_spec.rb'
    - 'Guardfile'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/linked_list.rb'
    - 'lib/node.rb'
